site_name: MkDocs Material Olson
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  extra: 
    social:
      - icon: GitHub-Logos\GitHub-Logos\GitHub_Logo_White.png
        link: C:\Users\OGilliam\Downloads\GitHub-Logos\GitHub-Logos
      - icon: fontawesome/brands/twitter
        link: https://github.com/StarlordKorn/mkdocs-material-olson
      - icon: fontawesome/brands/linkedin
        link: https://github.com/StarlordKorn/mkdocs-material-olson

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
 
